# single neural
### A single neural (or single neuron) is the basic computational unit in a neural network that receives multiple inputs, applies weights to them, sums them, and passes the result through an activation function to produce an output.

In [1]:
inputs = [1,2,3]
weights = [0.2,0.8,-0.5]
bias = 2 # it helps to move the backward and forward

In [3]:
output = inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

2.3


# adding an input

In [6]:
inputs = [1,2,3, 2.5]
weights = [0.2,0.8, -0.5,1.0]
bias = 2

In [8]:
output = inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
print(output)

4.8


## Layer of neural

In [12]:
inputs = [1,2,3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

In [13]:
outputs = [
    # first neuron
    inputs[0] * weights1[0]+
    inputs[1] * weights1[1]+
    inputs[2] * weights1[2]+
    inputs[3] * weights1[3]+ bias1 ,

    # second
    inputs[0] * weights2[0]+
    inputs[1] * weights2[1]+
    inputs[2] * weights2[2]+
    inputs[3] * weights2[3]+ bias2,

    # third neuron
    inputs[0] * weights3[0]+
    inputs[1] * weights3[1]+
    inputs[2] * weights3[2]+
    inputs[3] * weights3[3]+ bias3
    
]

In [14]:
print(outputs)

[4.8, 1.21, 2.385]


## calculating through loops

In [24]:
inputs = [1,2,3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

In [25]:
layers_output = []

In [26]:
# for each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # setting a variable
    neuron_output = 0
    # for each input and weight 
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input *  weight

    neuron_output +=  neuron_bias

    layers_output.append(neuron_output)

print(layers_output)

[4.8, 1.21, 2.385]


## dot product 2 vectors

In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3])
b = np.array([2,3,4])

In [8]:
a

array([1, 2, 3])

In [9]:
b

array([2, 3, 4])

In [10]:
np.dot(a,b)

np.int64(20)

## single layer with numpy

In [2]:
import numpy as np

In [7]:
inputs = [1.0,2.0,3.0,2.5]

In [8]:
weights = [
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26, -0.27,0.17,0.87]
]
biases = [2.0,3.0,0.5]

In [9]:
layer_output = np.dot(weights, inputs) + biases

In [10]:
print(layer_output)

[4.8   1.21  2.385]


## checking layer individualy

In [12]:
# layer 1
np.dot(weights[0],inputs)+ biases[0]

np.float64(4.8)

In [16]:
np.dot(weights[1],inputs)+ biases[1]

np.float64(1.21)

In [17]:
np.dot(weights[2],inputs)+ biases[2]

np.float64(2.385)

### multiplication by transpose

In [20]:
a= np.array([1,2,3])
b= np.array([2,3,4])

In [21]:
np.dot(a,b.T)

np.int64(20)

## Layer of neurons and batch of data

In [22]:
inputs = [
    [1.0,2.0,3.0,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]
]

weights = [
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]

In [23]:
biases = [2.0,3.0,0.5]

In [27]:
output = np.dot(inputs, np.array(weights).T)+biases

In [28]:
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

## adding layers

In [4]:
inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights1 = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases1 = [2.0, 3.0, 0.5]

In [5]:
weights2 = [
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
]

biases2 = [-1, 2, 0.5]

In [6]:
layer1_outputs = np.dot(inputs, np.array(weights1).T) + biases1
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

In [8]:
layer2_outputs

array([[ 0.5031 , -1.04185, -1.03875],
       [ 0.2434 , -2.7332 , -4.7633 ],
       [-0.99314,  1.41254,  0.64345]])

In [10]:
np.array([
    [1, -1, -1],
    [1, -1,-1],
    [-1, 1, 1]
])

array([[ 1, -1, -1],
       [ 1, -1, -1],
       [-1,  1,  1]])